# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ python ]
  pull_request:
    branches: [ python ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Install IBM Cloud CLI
        run: curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        shell: bash
      - name: Install Cloud Foundry CLI
        run: ibmcloud cf install
        shell: bash
      - name: Authenticate with IBM Cloud CLI
        run: ibmcloud login --apikey GrLy5OEAY46tyNU51plJnmd-k_cxrfZgvaQP3vLXzKEu --no-region -g Default
        shell: bash
      - name: Target a Cloud Foundry org and space
        run: ibmcloud target --cf-api https://api.eu-gb.cf.cloud.ibm.com -o schokokex -s dev
        shell: bash
      - name: Deploy to Cloud Foundry
        run: ibmcloud cf push cloudy-files-bot-py
        shell: bash
